version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - caiyin_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - caiyin_static:/data/static/
      - caiyin_media:/data/media/
      - caiyin_log:/var/log/nginx/

  goaccess:
    image: allinurl/goaccess:1.5.2
    volumes:
      - gis_log:/var/log/nginx/
    ports:
      - 7890:7890
    command: /var/log/nginx/gis_access.log -o /var/log/nginx/report.html --log-format=COMBINED --real-time-html

  django:
    image: caiyin_django:5
    networks:
      - caiyin_network
    volumes:
      - caiyin_static:/home/gis/staticfiles/
      - caiyin_media:/home/gis/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - caiyin_network
    volumes:
      - caiyin_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD

networks:
  caiyin_network:

volumes:
  caiyin_static:
  caiyin_media:
  caiyin_mariadb:
  caiyin_log:
  gis_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true